---
deployment:
  tasks:
    - export DEPLOYPATH=/home/fanadigi/public_html/FANADIGITAL/PRODUCT/LINKPOST
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp config.php $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R id $DEPLOYPATH
    - /bin/cp -R themes $DEPLOYPATH
    - /bin/cp -R uploads $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH